openapi: 3.0.0
info:
  title: MyPharmacy API
  version: 1.0.0
  description: |
    RESTful backend API for user authentication, medicine catalog, pharmacy locations, and order processing.
    
    ## Features
    - User authentication and authorization
    - Medicine catalog management
    - Pharmacy location services
    - Order processing and tracking
    - Secure API with rate limiting and CSRF protection

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://your-production-url.onrender.com
    description: Production server

paths:
  /api/users/register:
    post:
      $ref: './paths/auth/register.yaml'
  /api/users/login:
    post:
      $ref: './paths/auth/login.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Access token received after successful login/registration.
        Enter your access token (without "Bearer " prefix).
        **Note:** This token is automatically returned after authentication and stored in your client.
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
      description: |
        Refresh token automatically set as HTTP-only cookie after login/registration.
        **Note:** This is handled automatically by the browser - no manual input required.
    csrfToken:
      type: apiKey
      in: header
      name: X-CSRF-Token
      description: |
        CSRF protection token received after login/registration.
        **Note:** This token is returned in the response and should be included in subsequent requests.

  # schemas and responses are defined inline in path files